### ISSUE TITLE
checkPwned not working.

### ISSUE THREAD

**Issue by thedavidthomas** [riasvdv/craft-password-policy#10]
It looks like the Pwned passwords public API has changed and no longer supports searching for passwords by plain text it was discontinued on the 1st of June 2018.

You now need to search by range
https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange

Related Posts:
https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/
https://www.troyhunt.com/enhancing-pwned-passwords-privacy-by-exclusively-supporting-anonymity/
https://blog.cloudflare.com/validating-leaked-passwords-with-k-anonymity/

**Comment by lenvanessen** [comment]
PR 11 fixes this
