### ISSUE TITLE
Feature Request: Force Password Update every 90 days

### ISSUE THREAD

**Issue by brianrivet-tilt** [riasvdv/craft-password-policy#24]
Hi,

I have a couple of projects coming up that could use a plugin like this, but there is a feature we are looking for that I was hoping you might consider adding. It might be nice to have a feature where you could force users to have to reset their password every 90 days or possibly on an interval you could set in a config somehow.

Thanks!

**Comment by cookie10codes** [comment]
hi @brianrivet-tilt,

Thank you for your interest in our plugin, sorry about the delay. You're feature has been integrated within the plugin.

You can switch on the "Force Password Reset" lightswitch in the settings. You can manually run `./craft password-policy/password-reset/default` or create a cronjob with this command. This will check if the last password save is older than the days specified in the settings (default 90 days).

Let me know if you have any questions
