### ISSUE TITLE
Feature Request: use password strenght bar on front-end forms

### ISSUE THREAD

**Issue by S-n-d** [riasvdv/craft-password-policy#25]
Great plugin guys!

Would be awesome if there was a way to also use the password strength bar on front-end user registration forms, just like in the control panel. Any hints?

**Comment by cookie10codes** [comment]
hi @S-n-d,

Thank you! We're using zxcvbn under the hood, you can implement it into your frontend https://github.com/dropbox/zxcvbn

**Comment by S-n-d** [comment]
@cookie10codes thanks for the suggestion! Cheers!

**Comment by cookie10codes** [comment]
no worries @S-n-d, it's just as simple as `zxcvbn.score('passdownyourpasswordasastring')`

**Comment by bartrylant** [comment]
While it's possible to implement it by yourself on the front-end, it would be nice if it would be just a toggle button in the settings, since the script and all code for the strength bar are in the plugin anyway.
