### ISSUE TITLE
Missing Have I been Pwned Feature

### ISSUE THREAD

**Issue by FabianTUW** [riasvdv/craft-password-policy#29]
Hi,

in your README.md you say that "This plugin can also check the [Have I been Pwned database](https://haveibeenpwned.com/Passwords)". 
As far as I can see, this is no longer the case since you removed this functionality in [this commit](https://github.com/craftpulse/craft-password-policy/commit/30ce0617f3e54d7980d6f3bcc01c148f6dbbd0ee).

Could you please reintroduce this functionality?

**Comment by michtio** [comment]
@FabianTUW this has been reintroduced in the new 5.0.2 release for Craft 5. The reason this left was because this was using an old abandoned package, which gave issues with Craft's standard packages. This has been refactored and implemented through the k-anonymity principle of Have I been Pwned.

**Comment by FabianTUW** [comment]
Thank you so much. I love to see it
