### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by joelzerner** [riasvdv/craft-password-policy#30]
Just checking to see if this plugin will be ported to Craft 5 and if so, what the timing is?

**Comment by michtio** [comment]
@joelzerner - this will be ported. We kind of missed the release timeframe. As our original planning was releasing support in the first week of April.

So it's coming soon!

**Comment by vonscriptor** [comment]
Great, thanks for the update!

**Comment by michtio** [comment]
Password Policy for Craft 5 is being tested as we speak. Release is scheduled for this Friday!

**Comment by vonscriptor** [comment]
Any updates for us on its release? Thanks!

**Comment by michtio** [comment]
@vonscriptor you can actually install it if you want. We have some issues with our connection to the Craft Plugin store, which doesn't want to update automatically. 

https://github.com/craftpulse/craft-password-policy/releases/tag/5.0.0-beta1

If you tag it as `"^5.0.0-beta1"` it will install.
